name: progetto_mobile_programming
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2777.1
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  sqflite: ^2.3.3+1
  fl_chart: ^0.68.0
  http: ^1.2.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_local_notifications: ^13.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path_android: "assets/identity/logo.png"
  image_path_ios: "assets/identity/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/identity/
