// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqURaTgImZDM2aogrpI1-YBUma3p44-A',
    appId: '1:1021244629365:android:940540cedfd6c674b0f33c',
    messagingSenderId: '1021244629365',
    projectId: 'mppushnotification',
    storageBucket: 'mppushnotification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJf8DY1Ov8_Wxwjld2mA2spo5jsvTsEo',
    appId: '1:1021244629365:ios:2ddcc85201bea6c0b0f33c',
    messagingSenderId: '1021244629365',
    projectId: 'mppushnotification',
    storageBucket: 'mppushnotification.appspot.com',
    iosBundleId: 'com.example.progettoMobileProgramming',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEsFEYmrWr29uRdlz262A7Pp6BnUo3Fbs',
    appId: '1:1067442811457:web:f9cb87817c25bef59e8cc0',
    messagingSenderId: '1067442811457',
    projectId: 'pushnotificationmp',
    authDomain: 'pushnotificationmp.firebaseapp.com',
    storageBucket: 'pushnotificationmp.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYIHsECFGhfCfzue0NxFTAHBojQ844T9Q',
    appId: '1:1067442811457:ios:95152e5a92fb01a59e8cc0',
    messagingSenderId: '1067442811457',
    projectId: 'pushnotificationmp',
    storageBucket: 'pushnotificationmp.appspot.com',
    iosBundleId: 'com.example.progettoMobileProgramming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEsFEYmrWr29uRdlz262A7Pp6BnUo3Fbs',
    appId: '1:1067442811457:web:d112ea2b773f87a69e8cc0',
    messagingSenderId: '1067442811457',
    projectId: 'pushnotificationmp',
    authDomain: 'pushnotificationmp.firebaseapp.com',
    storageBucket: 'pushnotificationmp.appspot.com',
  );

}